import os
from pathlib import Path


CODE_DIR = Path(__file__).resolve().parent
DATASET_DIR = Path(os.getenv("GULLY_DATASET_DIR", CODE_DIR / "datasets")).resolve()
OUTPUT_DIR = Path(os.getenv("GULLY_OUTPUT_DIR", CODE_DIR / "output")).resolve()

TRAIN_IMAGE_DIR = DATASET_DIR / "train" / "images"
TRAIN_LABEL_DIR = DATASET_DIR / "train" / "labels"
VAL_IMAGE_DIR = DATASET_DIR / "val" / "images"
VAL_LABEL_DIR = DATASET_DIR / "val" / "labels"
TEST_IMAGE_DIR = DATASET_DIR / "test" / "images"
TEST_LABEL_DIR = DATASET_DIR / "test" / "labels"

MODEL_NAME = "EfficientUNet"
ENCODER_NAME = "efficientnet-b4"
NUM_CLASSES = 2
USE_MIXED_ACTIVATION = True
PRETRAINED_ENCODER = True

SEED = 701
BATCH_SIZE = 4
IMAGE_SIZE = 256
LEARNING_RATE = 1e-4
EPOCHS = 100
WEIGHT_DECAY = 0.01
LR_SCHEDULER_FACTOR = 0.5
LR_SCHEDULER_PATIENCE = 10
EARLY_STOPPING_PATIENCE = 20
EARLY_STOPPING_MIN_DELTA = 0.001

MODEL_OUTPUT_DIR = OUTPUT_DIR / MODEL_NAME
BEST_CHECKPOINT = MODEL_OUTPUT_DIR / "best.pth"
LAST_CHECKPOINT = MODEL_OUTPUT_DIR / "last.pth"
PREDICTION_DIR = MODEL_OUTPUT_DIR / "predictions"
TEST_RESULT = MODEL_OUTPUT_DIR / "test_metrics.json"
